### ISSUE TITLE
Issue creating blacklist exclusion mode

### ISSUE THREAD

**Issue by AlexaTheRaichu** [griffenx/CityZen#2]
As the city mayor, I am unable to set the exclusion mode to blacklist for Laverre City. It returns the message that I must be the mayor to do that. 
![2016-02-07_13 08 36](https://cloud.githubusercontent.com/assets/17112805/12874964/c2dc885e-cd9c-11e5-81d9-2ce72313e175.png)

**Comment by baph-omet** [comment]
Looks like I had a condition set incorrectly for this command. This should be fixed on the next commit.

**Comment by baph-omet** [comment]
Should now be fixed. Please confirm.
