### ISSUE TITLE
Just a few bugs

### ISSUE THREAD

**Issue by tylerking** [griffenx/CityZen#6]
Loving this plugin so wanted to report bugs as I found them.

Bugs:
- Upon entering the world I'm always shown this message: "You have X unread Alerts! Type /alert to read." But when I use /alert it says "You must supply a message".
- When a player attempts to join a city with FreeJoin set to false it naturally denies but it doesn't inform that a player sent a request to join. If I use the command to accept their request it also tells me that player hasn't send any request to join. However, It does seem to add an entry to the list of unread alerts that I'm unable to read.

Update: I did indeed update to the new version of the plugin.

**Comment by baph-omet** [comment]
Ok, so for the first issue, it seems like you're trying to run the command `/city alert` instead of `/alert`. The former is used for city officials to send alerts to residents of their city, and the latter is used by everyone to access stored alerts. If this is not the case, I will take a look at this later when I have full code access (I'm at work ATM).

The second one, I'm not sure about, but I can take a look at it later.

Thanks for reporting.

**Comment by tylerking** [comment]
Hey there. I actually tried both commands so something is definitely going on there. Thanks for having a look.

**Comment by baph-omet** [comment]
Both commands give you the same result? If so, that's definitely not right.

**Comment by tylerking** [comment]
Nope. When I type /alert it says "You must supply a message". When I type /city alert it says "Not enough arguments. Useage: /city alert <message>".

Here is a screenshot of me logging on:
http://i.imgur.com/gJVt9T7.png

**Comment by baph-omet** [comment]
Ok, I'm pretty confident that the message you are seeing is not from CityZen. I'm looking through my copy of the code here on Github (which isn't 100% up to date, but I haven't modified either of those commands in a while so it should be accurate) and I can't find the "You must supply a message" message. It seems like `/alert` is being registered by another plugin, which would explain the odd message. CityZen has an alias for this command: `/alerts`. I'm not sure what plugin could be hogging this command registration, but you might want to see if this alias works.

**Comment by tylerking** [comment]
Ok cool. That alias works but the other problem still persists. Here is a screenshot of that:

http://i.imgur.com/8l2vds8.png

**Comment by baph-omet** [comment]
Alright, I found the problem. Looks like players weren't being added to city waitlists correctly (a dumb mistake on my part). This should be fixed in the lastest commit and I'll go ahead and push out an update to BukkitDev and Spigot.

**Comment by tylerking** [comment]
Great news. Thanks!

**Comment by baph-omet** [comment]
If you want to go ahead and download the update, you can find it at https://github.com/griffenx/CityZen/blob/master/target/CityZen-1.0.2.jar. Just click "View Raw" to download it. I'd actually like to know if this fixes the issue before I issue an official update (it _should_, but just to be safe)

**Comment by baph-omet** [comment]
Updates have now been uploaded to Spigot and Bukkit. Let me know if this issue is resolved.

**Comment by tylerking** [comment]
Works perfectly. Thanks for the speedy update. If anything else arises I'll let you know.
